package com.myspace.ttereport;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Datamodel implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Datamodel() {
    }




}