package com.myspace.ttereport;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Email implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String str;

	private java.lang.String str1;

	private java.lang.String pl;

	public Email() {
	}

	public java.lang.String getStr() {
		return this.str;
	}

	public void setStr(java.lang.String str) {
		this.str = str;
	}

	public java.lang.String getStr1() {
		return this.str1;
	}

	public void setStr1(java.lang.String str1) {
		this.str1 = str1;
	}

	public java.lang.String getPl() {
		return this.pl;
	}

	public void setPl(java.lang.String pl) {
		this.pl = pl;
	}

	public Email(java.lang.String str, java.lang.String str1,
			java.lang.String pl) {
		this.str = str;
		this.str1 = str1;
		this.pl = pl;
	}

}