package com.myspace.ttereport;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Home implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String list;

	private java.lang.Boolean flag;

	private java.util.List<java.lang.String> first;

	private java.util.List<java.lang.String> second;

	private java.lang.String date;

	public java.lang.Integer tomer;

	public Home() {
	}

	public java.lang.String getList() {
		return this.list;
	}

	public void setList(java.lang.String list) {
		this.list = list;
	}

	public java.lang.Boolean getFlag() {
		return this.flag;
	}

	public void setFlag(java.lang.Boolean flag) {
		this.flag = flag;
	}

	public java.util.List<java.lang.String> getFirst() {
		return this.first;
	}

	public void setFirst(java.util.List<java.lang.String> first) {
		this.first = first;
	}

	public java.util.List<java.lang.String> getSecond() {
		return this.second;
	}

	public void setSecond(java.util.List<java.lang.String> second) {
		this.second = second;
	}

	public java.lang.String getDate() {
		return this.date;
	}

	public void setDate(java.lang.String date) {
		this.date = date;
	}

	public java.lang.Integer getTomer() {
		return this.tomer;
	}

	public void setTomer(java.lang.Integer tomer) {
		this.tomer = tomer;
	}

	public Home(java.lang.String list, java.lang.Boolean flag,
			java.util.List<java.lang.String> first,
			java.util.List<java.lang.String> second, java.lang.String date,
			java.lang.Integer tomer) {
		this.list = list;
		this.flag = flag;
		this.first = first;
		this.second = second;
		this.date = date;
		this.tomer = tomer;
	}

}