package com.myspace.ttereport;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Present1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String str;

	public Present1() {
	}

	public java.lang.String getStr() {
		return this.str;
	}

	public void setStr(java.lang.String str) {
		this.str = str;
	}

	public Present1(java.lang.String str) {
		this.str = str;
	}

}