package com.myspace.ttereport;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class testing implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<java.lang.String> a;
	private java.lang.String temp;

	private java.util.List<java.lang.String> second;

	public testing() {
	}

	public String getA() {
		setTemp("<tr><td>Sr. NO.</td><td>Name</td><td>Time</td></tr>");
		for (int i = 0; i < a.size(); i++) {
			StringBuilder sb = new StringBuilder();
			sb.append((String) a.get(i));
			String res = sb.toString();
			String[] arr = res.split(",");

			temp = temp + "<tr>" + "<td>" + (i + 1) + "</td>" + "<td>" + arr[0]
					+ "</td>" + "<td>" + arr[1] + "</td>" + "</tr>";
		}

		return temp;
	}

	public void setA(java.util.List<java.lang.String> a) {
		this.a = a;
	}

	public java.lang.String getTemp() {
		return this.temp;
	}

	public void setTemp(java.lang.String temp) {
		this.temp = temp;
	}

	public java.util.List<java.lang.String> getSecond() {
		return this.second;
	}

	public void setSecond(java.util.List<java.lang.String> second) {
		this.second = second;
	}

	public testing(java.util.List<java.lang.String> a, java.lang.String temp,
			java.util.List<java.lang.String> second) {
		this.a = a;
		this.temp = temp;
		this.second = second;
	}

}